// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pr-reviewer-assignment-service.git/internal/domain"
)

// NewMockPRStorage creates a new instance of MockPRStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRStorage {
	mock := &MockPRStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPRStorage is an autogenerated mock type for the PRStorage type
type MockPRStorage struct {
	mock.Mock
}

type MockPRStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRStorage) EXPECT() *MockPRStorage_Expecter {
	return &MockPRStorage_Expecter{mock: &_m.Mock}
}

// AssignReviewers provides a mock function for the type MockPRStorage
func (_mock *MockPRStorage) AssignReviewers(ctx context.Context, prID string, reviewersIDs []string) error {
	ret := _mock.Called(ctx, prID, reviewersIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignReviewers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, prID, reviewersIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPRStorage_AssignReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignReviewers'
type MockPRStorage_AssignReviewers_Call struct {
	*mock.Call
}

// AssignReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - reviewersIDs []string
func (_e *MockPRStorage_Expecter) AssignReviewers(ctx interface{}, prID interface{}, reviewersIDs interface{}) *MockPRStorage_AssignReviewers_Call {
	return &MockPRStorage_AssignReviewers_Call{Call: _e.mock.On("AssignReviewers", ctx, prID, reviewersIDs)}
}

func (_c *MockPRStorage_AssignReviewers_Call) Run(run func(ctx context.Context, prID string, reviewersIDs []string)) *MockPRStorage_AssignReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPRStorage_AssignReviewers_Call) Return(err error) *MockPRStorage_AssignReviewers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPRStorage_AssignReviewers_Call) RunAndReturn(run func(ctx context.Context, prID string, reviewersIDs []string) error) *MockPRStorage_AssignReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function for the type MockPRStorage
func (_mock *MockPRStorage) CreatePR(ctx context.Context, prID string, prName string, authorID string) error {
	ret := _mock.Called(ctx, prID, prName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, prID, prName, authorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPRStorage_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockPRStorage_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - prName string
//   - authorID string
func (_e *MockPRStorage_Expecter) CreatePR(ctx interface{}, prID interface{}, prName interface{}, authorID interface{}) *MockPRStorage_CreatePR_Call {
	return &MockPRStorage_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, prID, prName, authorID)}
}

func (_c *MockPRStorage_CreatePR_Call) Run(run func(ctx context.Context, prID string, prName string, authorID string)) *MockPRStorage_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPRStorage_CreatePR_Call) Return(err error) *MockPRStorage_CreatePR_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPRStorage_CreatePR_Call) RunAndReturn(run func(ctx context.Context, prID string, prName string, authorID string) error) *MockPRStorage_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRAuthorID provides a mock function for the type MockPRStorage
func (_mock *MockPRStorage) GetPRAuthorID(ctx context.Context, prID string) (string, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRAuthorID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRStorage_GetPRAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRAuthorID'
type MockPRStorage_GetPRAuthorID_Call struct {
	*mock.Call
}

// GetPRAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPRStorage_Expecter) GetPRAuthorID(ctx interface{}, prID interface{}) *MockPRStorage_GetPRAuthorID_Call {
	return &MockPRStorage_GetPRAuthorID_Call{Call: _e.mock.On("GetPRAuthorID", ctx, prID)}
}

func (_c *MockPRStorage_GetPRAuthorID_Call) Run(run func(ctx context.Context, prID string)) *MockPRStorage_GetPRAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRStorage_GetPRAuthorID_Call) Return(s string, err error) *MockPRStorage_GetPRAuthorID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPRStorage_GetPRAuthorID_Call) RunAndReturn(run func(ctx context.Context, prID string) (string, error)) *MockPRStorage_GetPRAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function for the type MockPRStorage
func (_mock *MockPRStorage) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, oldReviewerID, newReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRStorage_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type MockPRStorage_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
//   - newReviewerID string
func (_e *MockPRStorage_Expecter) ReassignReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}, newReviewerID interface{}) *MockPRStorage_ReassignReviewer_Call {
	return &MockPRStorage_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, prID, oldReviewerID, newReviewerID)}
}

func (_c *MockPRStorage_ReassignReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string)) *MockPRStorage_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPRStorage_ReassignReviewer_Call) Return(pullRequest *domain.PullRequest, err error) *MockPRStorage_ReassignReviewer_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPRStorage_ReassignReviewer_Call) RunAndReturn(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (*domain.PullRequest, error)) *MockPRStorage_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatusMerged provides a mock function for the type MockPRStorage
func (_mock *MockPRStorage) SetStatusMerged(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for SetStatusMerged")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRStorage_SetStatusMerged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusMerged'
type MockPRStorage_SetStatusMerged_Call struct {
	*mock.Call
}

// SetStatusMerged is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPRStorage_Expecter) SetStatusMerged(ctx interface{}, prID interface{}) *MockPRStorage_SetStatusMerged_Call {
	return &MockPRStorage_SetStatusMerged_Call{Call: _e.mock.On("SetStatusMerged", ctx, prID)}
}

func (_c *MockPRStorage_SetStatusMerged_Call) Run(run func(ctx context.Context, prID string)) *MockPRStorage_SetStatusMerged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRStorage_SetStatusMerged_Call) Return(pullRequest *domain.PullRequest, err error) *MockPRStorage_SetStatusMerged_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPRStorage_SetStatusMerged_Call) RunAndReturn(run func(ctx context.Context, prID string) (*domain.PullRequest, error)) *MockPRStorage_SetStatusMerged_Call {
	_c.Call.Return(run)
	return _c
}
