// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserStorage creates a new instance of MockUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStorage {
	mock := &MockUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStorage is an autogenerated mock type for the UserStorage type
type MockUserStorage struct {
	mock.Mock
}

type MockUserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStorage) EXPECT() *MockUserStorage_Expecter {
	return &MockUserStorage_Expecter{mock: &_m.Mock}
}

// GetPotentialReviewersIDs provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) GetPotentialReviewersIDs(ctx context.Context, authorID string, userID string, limit int) ([]string, error) {
	ret := _mock.Called(ctx, authorID, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPotentialReviewersIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]string, error)); ok {
		return returnFunc(ctx, authorID, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []string); ok {
		r0 = returnFunc(ctx, authorID, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, authorID, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStorage_GetPotentialReviewersIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPotentialReviewersIDs'
type MockUserStorage_GetPotentialReviewersIDs_Call struct {
	*mock.Call
}

// GetPotentialReviewersIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - userID string
//   - limit int
func (_e *MockUserStorage_Expecter) GetPotentialReviewersIDs(ctx interface{}, authorID interface{}, userID interface{}, limit interface{}) *MockUserStorage_GetPotentialReviewersIDs_Call {
	return &MockUserStorage_GetPotentialReviewersIDs_Call{Call: _e.mock.On("GetPotentialReviewersIDs", ctx, authorID, userID, limit)}
}

func (_c *MockUserStorage_GetPotentialReviewersIDs_Call) Run(run func(ctx context.Context, authorID string, userID string, limit int)) *MockUserStorage_GetPotentialReviewersIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserStorage_GetPotentialReviewersIDs_Call) Return(strings []string, err error) *MockUserStorage_GetPotentialReviewersIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUserStorage_GetPotentialReviewersIDs_Call) RunAndReturn(run func(ctx context.Context, authorID string, userID string, limit int) ([]string, error)) *MockUserStorage_GetPotentialReviewersIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UserExistsAndHasTeam provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) UserExistsAndHasTeam(ctx context.Context, userID string) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserExistsAndHasTeam")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStorage_UserExistsAndHasTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExistsAndHasTeam'
type MockUserStorage_UserExistsAndHasTeam_Call struct {
	*mock.Call
}

// UserExistsAndHasTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserStorage_Expecter) UserExistsAndHasTeam(ctx interface{}, userID interface{}) *MockUserStorage_UserExistsAndHasTeam_Call {
	return &MockUserStorage_UserExistsAndHasTeam_Call{Call: _e.mock.On("UserExistsAndHasTeam", ctx, userID)}
}

func (_c *MockUserStorage_UserExistsAndHasTeam_Call) Run(run func(ctx context.Context, userID string)) *MockUserStorage_UserExistsAndHasTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStorage_UserExistsAndHasTeam_Call) Return(b bool, err error) *MockUserStorage_UserExistsAndHasTeam_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserStorage_UserExistsAndHasTeam_Call) RunAndReturn(run func(ctx context.Context, userID string) (bool, error)) *MockUserStorage_UserExistsAndHasTeam_Call {
	_c.Call.Return(run)
	return _c
}
