// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pr-reviewer-assignment-service.git/internal/domain"
)

// NewMockPRStorage creates a new instance of MockPRStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRStorage {
	mock := &MockPRStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPRStorage is an autogenerated mock type for the PRStorage type
type MockPRStorage struct {
	mock.Mock
}

type MockPRStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRStorage) EXPECT() *MockPRStorage_Expecter {
	return &MockPRStorage_Expecter{mock: &_m.Mock}
}

// GetPRsReviewedBy provides a mock function for the type MockPRStorage
func (_mock *MockPRStorage) GetPRsReviewedBy(ctx context.Context, userID string) ([]*domain.PullRequest, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRsReviewedBy")
	}

	var r0 []*domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.PullRequest, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.PullRequest); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPRStorage_GetPRsReviewedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRsReviewedBy'
type MockPRStorage_GetPRsReviewedBy_Call struct {
	*mock.Call
}

// GetPRsReviewedBy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPRStorage_Expecter) GetPRsReviewedBy(ctx interface{}, userID interface{}) *MockPRStorage_GetPRsReviewedBy_Call {
	return &MockPRStorage_GetPRsReviewedBy_Call{Call: _e.mock.On("GetPRsReviewedBy", ctx, userID)}
}

func (_c *MockPRStorage_GetPRsReviewedBy_Call) Run(run func(ctx context.Context, userID string)) *MockPRStorage_GetPRsReviewedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPRStorage_GetPRsReviewedBy_Call) Return(pullRequests []*domain.PullRequest, err error) *MockPRStorage_GetPRsReviewedBy_Call {
	_c.Call.Return(pullRequests, err)
	return _c
}

func (_c *MockPRStorage_GetPRsReviewedBy_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.PullRequest, error)) *MockPRStorage_GetPRsReviewedBy_Call {
	_c.Call.Return(run)
	return _c
}
