// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pr-reviewer-assignment-service.git/internal/domain"
)

// NewMockUserStorage creates a new instance of MockUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStorage {
	mock := &MockUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStorage is an autogenerated mock type for the UserStorage type
type MockUserStorage struct {
	mock.Mock
}

type MockUserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStorage) EXPECT() *MockUserStorage_Expecter {
	return &MockUserStorage_Expecter{mock: &_m.Mock}
}

// SetIsActive provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) SetIsActive(ctx context.Context, userID string, isActive bool) (*domain.User, error) {
	ret := _mock.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.User, error)); ok {
		return returnFunc(ctx, userID, isActive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *domain.User); ok {
		r0 = returnFunc(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStorage_SetIsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIsActive'
type MockUserStorage_SetIsActive_Call struct {
	*mock.Call
}

// SetIsActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockUserStorage_Expecter) SetIsActive(ctx interface{}, userID interface{}, isActive interface{}) *MockUserStorage_SetIsActive_Call {
	return &MockUserStorage_SetIsActive_Call{Call: _e.mock.On("SetIsActive", ctx, userID, isActive)}
}

func (_c *MockUserStorage_SetIsActive_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockUserStorage_SetIsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserStorage_SetIsActive_Call) Return(user *domain.User, err error) *MockUserStorage_SetIsActive_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStorage_SetIsActive_Call) RunAndReturn(run func(ctx context.Context, userID string, isActive bool) (*domain.User, error)) *MockUserStorage_SetIsActive_Call {
	_c.Call.Return(run)
	return _c
}
