// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamStorage creates a new instance of MockTeamStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamStorage {
	mock := &MockTeamStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamStorage is an autogenerated mock type for the TeamStorage type
type MockTeamStorage struct {
	mock.Mock
}

type MockTeamStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamStorage) EXPECT() *MockTeamStorage_Expecter {
	return &MockTeamStorage_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function for the type MockTeamStorage
func (_mock *MockTeamStorage) CreateTeam(ctx context.Context, teamName string) error {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamStorage_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamStorage_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamStorage_Expecter) CreateTeam(ctx interface{}, teamName interface{}) *MockTeamStorage_CreateTeam_Call {
	return &MockTeamStorage_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, teamName)}
}

func (_c *MockTeamStorage_CreateTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamStorage_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamStorage_CreateTeam_Call) Return(err error) *MockTeamStorage_CreateTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamStorage_CreateTeam_Call) RunAndReturn(run func(ctx context.Context, teamName string) error) *MockTeamStorage_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// TeamExists provides a mock function for the type MockTeamStorage
func (_mock *MockTeamStorage) TeamExists(ctx context.Context, teamName string) (bool, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for TeamExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamStorage_TeamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamExists'
type MockTeamStorage_TeamExists_Call struct {
	*mock.Call
}

// TeamExists is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamStorage_Expecter) TeamExists(ctx interface{}, teamName interface{}) *MockTeamStorage_TeamExists_Call {
	return &MockTeamStorage_TeamExists_Call{Call: _e.mock.On("TeamExists", ctx, teamName)}
}

func (_c *MockTeamStorage_TeamExists_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamStorage_TeamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamStorage_TeamExists_Call) Return(b bool, err error) *MockTeamStorage_TeamExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTeamStorage_TeamExists_Call) RunAndReturn(run func(ctx context.Context, teamName string) (bool, error)) *MockTeamStorage_TeamExists_Call {
	_c.Call.Return(run)
	return _c
}
