// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pr-reviewer-assignment-service.git/internal/domain"
)

// NewMockUserStorage creates a new instance of MockUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStorage {
	mock := &MockUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStorage is an autogenerated mock type for the UserStorage type
type MockUserStorage struct {
	mock.Mock
}

type MockUserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStorage) EXPECT() *MockUserStorage_Expecter {
	return &MockUserStorage_Expecter{mock: &_m.Mock}
}

// GetUsersByTeamName provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) GetUsersByTeamName(ctx context.Context, teamName string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByTeamName")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStorage_GetUsersByTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByTeamName'
type MockUserStorage_GetUsersByTeamName_Call struct {
	*mock.Call
}

// GetUsersByTeamName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockUserStorage_Expecter) GetUsersByTeamName(ctx interface{}, teamName interface{}) *MockUserStorage_GetUsersByTeamName_Call {
	return &MockUserStorage_GetUsersByTeamName_Call{Call: _e.mock.On("GetUsersByTeamName", ctx, teamName)}
}

func (_c *MockUserStorage_GetUsersByTeamName_Call) Run(run func(ctx context.Context, teamName string)) *MockUserStorage_GetUsersByTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStorage_GetUsersByTeamName_Call) Return(users []*domain.User, err error) *MockUserStorage_GetUsersByTeamName_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserStorage_GetUsersByTeamName_Call) RunAndReturn(run func(ctx context.Context, teamName string) ([]*domain.User, error)) *MockUserStorage_GetUsersByTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUsers provides a mock function for the type MockUserStorage
func (_mock *MockUserStorage) UpsertUsers(ctx context.Context, users []*domain.User) error {
	ret := _mock.Called(ctx, users)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*domain.User) error); ok {
		r0 = returnFunc(ctx, users)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStorage_UpsertUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUsers'
type MockUserStorage_UpsertUsers_Call struct {
	*mock.Call
}

// UpsertUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - users []*domain.User
func (_e *MockUserStorage_Expecter) UpsertUsers(ctx interface{}, users interface{}) *MockUserStorage_UpsertUsers_Call {
	return &MockUserStorage_UpsertUsers_Call{Call: _e.mock.On("UpsertUsers", ctx, users)}
}

func (_c *MockUserStorage_UpsertUsers_Call) Run(run func(ctx context.Context, users []*domain.User)) *MockUserStorage_UpsertUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*domain.User
		if args[1] != nil {
			arg1 = args[1].([]*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStorage_UpsertUsers_Call) Return(err error) *MockUserStorage_UpsertUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStorage_UpsertUsers_Call) RunAndReturn(run func(ctx context.Context, users []*domain.User) error) *MockUserStorage_UpsertUsers_Call {
	_c.Call.Return(run)
	return _c
}
